spring:
  redis:
    timeout: 6000
    password: w123456
    cluster:
      max-redirects: 3 # 获取失败 最大重定向次数
      nodes:
        - 192.168.217.128:7001
        - 192.168.217.128:7002
        - 192.168.217.128:7003
        - 192.168.217.136:7004
        - 192.168.217.136:7005
        - 192.168.217.136:7006
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  cache:
    jcache:
      config: classpath:ehcache.xml